version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            -   app
        container_name: nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   postgresql
        container_name: app

    postgresql:
        image: postgres:latest
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
            - ./_docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf # Монтирование вашего конфигурационного файла
        environment:
            POSTGRES_DB: app_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres_password
        ports:
            - "8102:5432"
        container_name: postgresql
